feat: blog add sense-of-open-day
KusionStack/kusionstack.io pull request #51
Opened 2022-06-21 03:42 UTC by chai2010

#### 1. Does this PR affect any open issues?(Y/N) and add issue references (e.g. "fix #123", "re #123".):

- [ ] N
- [X] Y fix #44  

#### 2. What is the scope of this PR (e.g. component or file name):

#### 3. Provide a description of the PR(e.g. more details, effects, motivations or doc link):

- [ ] Affects user behaviors
- [ ] Contains syntax changes
- [ ] Contains variable changes
- [ ] Contains experimental features
- [ ] Performance regression: Consumes more CPU
- [ ] Performance regression: Consumes more Memory
- [X] Other: new post

#### 4. Are there any breaking changes?(Y/N) and describe the breaking changes(e.g. more details, motivations or doc link):

- [X] N
- [ ] Y 

#### 5. Are there test cases for these changes?(Y/N) select and add more details, references or doc links:

- [ ] Unit test
- [ ] Integration test
- [ ] Benchmark (add benchmark stats below)
- [ ] Manual test (add detailed scripts or steps below)
- [ ] Other

#### 6. Release note

Please refer to [Release Notes Language Style Guide](https://kusionstack.io/docs/governance/release-policy/) to write a quality release note.

```release-note
None
```

2022-06-21 11:16 UTC, howieyuen requested changes

2022-06-21 11:16 UTC, howieyuen commented on blog/2022-06-07-sense-of-open-day/index.md
> +  title: Kusion创始人
```suggestion
  title: Kusion 创始人
```

2022-06-21 11:16 UTC, howieyuen commented on blog/2022-06-07-sense-of-open-day/index.md
> +不同职能不同团队的参与者凝聚在一起解决各自所面对的问题，贡献了 3W+ commit 和 35W+ 行代码，有一些参与者自发成为 Kusion 的研发者 。我认为这些工程师文化理念和领域知识的积累带来了远超运维业务本身的价值。
```suggestion
不同职能不同团队的参与者凝聚在一起解决各自所面对的问题，贡献了 30k+ commit 和 350k+ 行代码，有一些参与者自发成为 Kusion 的研发者 。我认为这些工程师文化理念和领域知识的积累带来了远超运维业务本身的价值。
```

2022-06-21 11:16 UTC, howieyuen commented on blog/2022-06-07-sense-of-open-day/index.md
> +在未来， Kusion 的朋友圈不再局限于蚂蚁内部，面向开源，我们期待着能有更多的社区朋友在 KusionStack 与我们共同成长！
```suggestion
在未来，Kusion 的朋友圈不再局限于蚂蚁内部，面向开源，我们期待着能有更多的社区朋友在 KusionStack 与我们共同成长！
```

2022-06-21 13:18 UTC, chai2010 commented on blog/2022-06-07-sense-of-open-day/index.md
> +
fixed

2022-06-21 13:18 UTC, chai2010 commented on blog/2022-06-07-sense-of-open-day/index.md
> +  title: Kusion创始人
fixed

2022-06-21 13:18 UTC, chai2010 commented on blog/2022-06-07-sense-of-open-day/index.md
> +不同职能不同团队的参与者凝聚在一起解决各自所面对的问题，贡献了 3W+ commit 和 35W+ 行代码，有一些参与者自发成为 Kusion 的研发者 。我认为这些工程师文化理念和领域知识的积累带来了远超运维业务本身的价值。
fixed

2022-06-22 02:38 UTC, howieyuen approved these changes
LGTM

2022-06-22 03:00 UTC, merged